name: Release

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set up js runtime
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: install dependencies
        run: bun install

      - name: build
        run: cd  ./packages/app && bun run build

      - name: version
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MNM_JUICE_BAR }}'
          channelId: live
          projectId: mnm-juice-bar
          entryPoint: "./packages/app"
